language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install pytest pytest-cov
before_script:
  - cd python_programs/day_2/
script:
  - python -m pytest test_mymath.py -v --cov=mymath --cov-report=html
after_success:
  - coveralls