/* File: _unpackfmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Oct 19 11:01:54 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_unpackf_error;
static PyObject *_unpackf_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(_unpackf_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _unpackf_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(UNPACK,UNPACK)(int*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** UNPACK ***********************************/
static char doc_f2py_rout__unpackf_UNPACK[] = "\
UNPACK(SP,SQ,[N])\n\nWrapper for ``UNPACK``.\
\n\nParameters\n----------\n"
"SP : input rank-1 array('d') with bounds (*)\n"
"SQ : input rank-2 array('d') with bounds (N,N)\n"
"\nOther Parameters\n----------------\n"
"N : input int, optional\n    Default: shape(SQ,0)";
/* extern void F_FUNC(UNPACK,UNPACK)(int*,double*,double*); */
static PyObject *f2py_rout__unpackf_UNPACK(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int N = 0;
  PyObject *N_capi = Py_None;
  double *SP = NULL;
  npy_intp SP_Dims[1] = {-1};
  const int SP_Rank = 1;
  PyArrayObject *capi_SP_tmp = NULL;
  int capi_SP_intent = 0;
  PyObject *SP_capi = Py_None;
  double *SQ = NULL;
  npy_intp SQ_Dims[2] = {-1, -1};
  const int SQ_Rank = 2;
  PyArrayObject *capi_SQ_tmp = NULL;
  int capi_SQ_intent = 0;
  PyObject *SQ_capi = Py_None;
  static char *capi_kwlist[] = {"SP","SQ","N",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|O:_unpackf.UNPACK",\
    capi_kwlist,&SP_capi,&SQ_capi,&N_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable SQ */
  ;
  capi_SQ_intent |= F2PY_INTENT_IN;
  capi_SQ_tmp = array_from_pyobj(NPY_DOUBLE,SQ_Dims,SQ_Rank,capi_SQ_intent,SQ_capi);
  if (capi_SQ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_unpackf_error,"failed in converting 2nd argument `SQ' of _unpackf.UNPACK to C/Fortran array" );
  } else {
    SQ = (double *)(PyArray_DATA(capi_SQ_tmp));

  /* Processing variable SP */
  ;
  capi_SP_intent |= F2PY_INTENT_IN;
  capi_SP_tmp = array_from_pyobj(NPY_DOUBLE,SP_Dims,SP_Rank,capi_SP_intent,SP_capi);
  if (capi_SP_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_unpackf_error,"failed in converting 1st argument `SP' of _unpackf.UNPACK to C/Fortran array" );
  } else {
    SP = (double *)(PyArray_DATA(capi_SP_tmp));

  /* Processing variable N */
  if (N_capi == Py_None) N = shape(SQ,0); else
    f2py_success = int_from_pyobj(&N,N_capi,"_unpackf.UNPACK() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(SQ,0)==N,"shape(SQ,0)==N","1st keyword N","UNPACK:N=%d",N) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&N,SP,SQ);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(SQ,0)==N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  if((PyObject *)capi_SP_tmp!=SP_capi) {
    Py_XDECREF(capi_SP_tmp); }
  }  /*if (capi_SP_tmp == NULL) ... else of SP*/
  /* End of cleaning variable SP */
  if((PyObject *)capi_SQ_tmp!=SQ_capi) {
    Py_XDECREF(capi_SQ_tmp); }
  }  /*if (capi_SQ_tmp == NULL) ... else of SQ*/
  /* End of cleaning variable SQ */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of UNPACK *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"UNPACK",-1,{{-1}},0,(char *)F_FUNC(UNPACK,UNPACK),(f2py_init_func)f2py_rout__unpackf_UNPACK,doc_f2py_rout__unpackf_UNPACK},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_unpackf",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__unpackf(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_unpackf(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _unpackf_module = PyModule_Create(&moduledef);
#else
  m = _unpackf_module = Py_InitModule("_unpackf", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _unpackf (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_unpackf' is auto-generated with f2py (version:2).\nFunctions:\n"
"  UNPACK(SP,SQ,N=shape(SQ,0))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _unpackf_error = PyErr_NewException ("_unpackf.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_unpackf");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
